# Generated by Django 6.0.2 on 2026-02-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0002_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
    ]
